#!/bin/bash
source /usr/local/sbin/base-script

#Menu
merah="\e[1;31m"
kuning="\e[1;33m"
biru="\e[1;34m"
putih="\e[1;37m"
cyan="\e[1;36m"
clear
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
WKT=$(curl -s ipinfo.io/timezone )
IPVPS=$(curl -s ipinfo.io/ip )
jam=$(date +"%T")
hari=$(date +"%A")
tnggl=$(date +"%d-%B-%Y")
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "\E[41;1;30m              SYSTEM LOCAL INFO            \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "Waktu          : $jam"
echo -e "Hari           : $hari"
echo -e "Bulan          : $tnggl"
echo -e "ISP Name       : $ISP"
echo -e "City           : $CITY"
echo -e "IP VPS         : $IPVPS"
echo -e "DOMAIN/HOST    : $DOMAIN"
echo -e ""
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "\E[44;1;37m* Script       : VoltNet Premium Script \E[0m"
echo -e "\E[44;1;37m* menu         : List of Main Commands \E[0m"
echo -e ""
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "\E[41;1;30m             MENU PREMIUM SCRIPT           \E[0m"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "\E[44;1;37m             ALL PREMIUM MENU              \E[0m"
echo -e "$merah 1$putih. Menu-VPN          $biru(SSH/OVPN)"
echo -e "$merah 2$putih. Menu-WIREGUARD    $biru(WG)"
echo -e "$merah 3$putih. Menu-V2RAY/VMESS  $biru(VMESS)"
echo -e "$merah 4$putih. Menu-XRAY/VLESS   $biru(XTLS)\E[0m"
echo -e "$merah 5$putih. Menu-TROJAN/GFW   $biru(TROJAN)\E[0m"
echo -e "$merah 6$putih. Menu-SHADOWSOCKS  $biru(SS)"
echo -e "$merah 7$putih. Menu-SHADOWSOCKSR $biru(SSR)"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "\E[44;1;37m            SYSTEM NAVIGATOR          \E[0m"
echo -e "$merah 8$putih. SERVER       $biru(SERVER SETTINGS)"
echo -e "$merah 9$putih. OPTIONS      $biru(VPN SETTINGS)"
echo -e "$merah 10$putih. Display Info $biru(INFO)"
echo -e "$merah 11$putih. Info script  $biru(ABOUT)"
echo -e "$merah 12$putih. Edit banner  $biru(banner)\E[0m"
echo -e ""
echo -e "\e[46mTo exit the menu press CTRL + C \E[0m"
echo -e "$putih━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\E[0m"
read -p "   Select from options [1-12]: " Menu
echo -e ""
case $Menu in
		1)
		clear
		menu-vpn
		exit
		;;
		2)
		clear
		menu-wg
		exit
		;;
		3)
		clear
		menu-ws
		exit
		;;
		4)
		clear
		menu-xtls
		exit
		;;
		5)
		clear
		menu-tr
		exit
		;;
		6)
		clear
		menu-ss
		exit
		;;
		7)
		clear
		menu-ssr
		exit
		;;
		8)
		clear
		server
		exit
		;;
		9)
		clear
		options
		exit
		;;
		10)
		clear
		info
		exit
		;;
		11)
		clear
		about
		exit
		;;
		12)
		clear
		banner
		exit
		;;
		13)
		clear
		exit
		;;
	esac
